// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// ginv_cpp
NumericMatrix ginv_cpp(SEXP initialized_matrix, double tol);
RcppExport SEXP _SigBridgeRUtils_ginv_cpp(SEXP initialized_matrixSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type initialized_matrix(initialized_matrixSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(ginv_cpp(initialized_matrix, tol));
    return rcpp_result_gen;
END_RCPP
}
// matrix_summary_cpp
NumericVector matrix_summary_cpp(SEXP initialized_matrix, std::string statistic, bool by_row, bool na_rm);
RcppExport SEXP _SigBridgeRUtils_matrix_summary_cpp(SEXP initialized_matrixSEXP, SEXP statisticSEXP, SEXP by_rowSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type initialized_matrix(initialized_matrixSEXP);
    Rcpp::traits::input_parameter< std::string >::type statistic(statisticSEXP);
    Rcpp::traits::input_parameter< bool >::type by_row(by_rowSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_summary_cpp(initialized_matrix, statistic, by_row, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// matrix_quantiles_cpp
NumericMatrix matrix_quantiles_cpp(SEXP initialized_matrix, NumericVector probabilities, bool na_rm);
RcppExport SEXP _SigBridgeRUtils_matrix_quantiles_cpp(SEXP initialized_matrixSEXP, SEXP probabilitiesSEXP, SEXP na_rmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type initialized_matrix(initialized_matrixSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probabilities(probabilitiesSEXP);
    Rcpp::traits::input_parameter< bool >::type na_rm(na_rmSEXP);
    rcpp_result_gen = Rcpp::wrap(matrix_quantiles_cpp(initialized_matrix, probabilities, na_rm));
    return rcpp_result_gen;
END_RCPP
}
// normalize_quantiles_cpp
NumericMatrix normalize_quantiles_cpp(SEXP initialized_matrix);
RcppExport SEXP _SigBridgeRUtils_normalize_quantiles_cpp(SEXP initialized_matrixSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type initialized_matrix(initialized_matrixSEXP);
    rcpp_result_gen = Rcpp::wrap(normalize_quantiles_cpp(initialized_matrix));
    return rcpp_result_gen;
END_RCPP
}
// unpack_assign_cpp
void unpack_assign_cpp(SEXP lhs, SEXP rhs, Environment env);
RcppExport SEXP _SigBridgeRUtils_unpack_assign_cpp(SEXP lhsSEXP, SEXP rhsSEXP, SEXP envSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type lhs(lhsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type rhs(rhsSEXP);
    Rcpp::traits::input_parameter< Environment >::type env(envSEXP);
    unpack_assign_cpp(lhs, rhs, env);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SigBridgeRUtils_ginv_cpp", (DL_FUNC) &_SigBridgeRUtils_ginv_cpp, 2},
    {"_SigBridgeRUtils_matrix_summary_cpp", (DL_FUNC) &_SigBridgeRUtils_matrix_summary_cpp, 4},
    {"_SigBridgeRUtils_matrix_quantiles_cpp", (DL_FUNC) &_SigBridgeRUtils_matrix_quantiles_cpp, 3},
    {"_SigBridgeRUtils_normalize_quantiles_cpp", (DL_FUNC) &_SigBridgeRUtils_normalize_quantiles_cpp, 1},
    {"_SigBridgeRUtils_unpack_assign_cpp", (DL_FUNC) &_SigBridgeRUtils_unpack_assign_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_SigBridgeRUtils(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
